var UI = {
  Panel: {
    show: function( parent,
                    default_ref_selection = 'all',
                    is_context_menu = false )
    {
      this._panel = d3.select('#vislink-panel');
      //panel.select('.info').text( JSON.stringify([...concept_graph.selection]) );

      var self = this;
      this._panel.select('.selection')
        .on('DOMAttrModified', function()
        {
          if(    d3.event.target != d3.event.originalTarget
              || d3.event.attrName != 'checked' )
            return;

          self._update();
        });

      var selection_items =
        this._panel
        .select('.selection')
        .selectAll('li')
        .data([...concept_graph.getSelection()].sort(function(lhs, rhs)
        {
          if( lhs.getType() != rhs.getType() )
            return lhs.isRelation();
          else
            return lhs.id > rhs.id;
        }));

      selection_items.enter()
        .append('li')
        .append('checkbox');
      selection_items.exit()
        .remove();

      selection_items.each(function(d)
      {
        var self = d3.select(this);

        self.select('checkbox')
          .attr('id', function(d) { return 'ref-check-' + d.id; })
          .attr('label', function(d)
          {
            return d.getLabel();
          })
          .attr('checked', true);
        self
          .classed('concept', function(d) { return d.isConcept(); })
          .classed('relation', function(d) { return d.isRelation(); })
          .style('background-color', function(d) { return d.getColor(); })
          .style('color', function(d) { return contrastColor(d.getColor()); });
      });

      if( !content.getSelection().isCollapsed )
      {
        $('sec-ref-scope').hidden = false;
        $('ref-scope').selectedItem = (default_ref_selection == 'selection')
                                    ? $('ref-selection')
                                    : $('ref-all');
      }
      else
        $('sec-ref-scope').hidden = true;

      this._update();
      this._panel.node().openPopup(
        parent,
        'bottomcenter topright',
        0, 0,
        is_context_menu,
        false
      );
    },
    getSelection: function()
    {
      var selection = new Set();
      this._panel
        .select('.selection')
        .selectAll('checkbox[checked=true]')
        .each(function(d)
        {
          selection.add(d);
        });
      return selection;
    },

    /** Get selection ids as array (with ids of relations beeing arrays of node
     *  ids)
     */
    getSelectionIdArray: function()
    {
      var ids = [];
      for(var item of this.getSelection())
        if( item.isConcept() )
          ids.push(item.id);
        else
          ids.push(item.nodes);
      return ids;
    },
    _onAddReference: function(button)
    {
      utils.addReference(this.getSelectionIdArray(), $('ref-scope').value);
      this._panel.node().hidePopup();
    },
    _onCreateRelation: function(button)
    {
      utils.addRelation(this.getSelectionIdArray(), $('ref-scope').value);
      this._panel.node().hidePopup();
    },
    _onCreateConcept: function(button)
    {
      utils.addConcept($('ref-scope').value);
      this._panel.node().hidePopup();
    },
    _update: function()
    {
      var selection = this.getSelection();
      var concept_count = 0,
          relation_count = 0;

      for(var item of selection)
      {
        if( item.isConcept() )
          concept_count += 1;
        else
          relation_count += 1;
      }

      $('btn-create-relation').disabled = relation_count || concept_count != 2;
      $('btn-add-reference').disabled = !relation_count && !concept_count;

      var hide_selection_actions = !concept_graph.getSelection().size;
      $('btn-create-relation').hidden = hide_selection_actions;
      $('btn-add-reference').hidden = hide_selection_actions;
      $('sec-selection').hidden = hide_selection_actions;
    }
  },
  showPreferences: function()
  {
    window.open( 'chrome://hidden-content/content/preferences.xul',
                 'VisLinks - Settings',
                 'chrome' );
  },
  onToolButtonClick: function(button, event)
  {
    // Ignore events generated by clicking an menu entry
    if( event.target != button )
      return;

    if( status != 'active' )
      start();
    else
      UI.Panel.show(button);
  }
};